### ISSUE TITLE
Better Sidebar - slight issue

### ISSUE THREAD

**Issue by mepsyche** [cannibalox/logseq-custom-files#11]
hello!  I just want to first say thank you so much for the better sidebar! It was exactly what I needed! 

HOWEVER, For some reason, when I "collapse" a page it will not open again!  

I did not previously have a .js file - so I simply downloaded yours and put it in the logseq folder.

I did have a custom.css file for a theme I am using, so I simply copied yours and added it to the bottom.  

I have attached the .js & the .css files I am using.  I'd appreciate any help!! 

====

[custom css.txt](https://github.com/cannibalox/logseq-custom-files/files/11992310/custom.css.txt)
[custom js.txt](https://github.com/cannibalox/logseq-custom-files/files/11992311/custom.js.txt)

**Comment by cannibalox** [comment]
Thankf for the report. I take that you are using logseq 0.9.10 ? there were some adjusments that broke the rotating arrows location (the hit box was located above the arrow, so you had to aim a bit higher to trigger the unfolding).
I've pushed a fix that will hopefully address your issue, update your custom.css with the new version from 2023/07/09 and let me know if it works.
