### ISSUE TITLE
Sidebar not horizontal in 0.10

### ISSUE THREAD

**Issue by Cacuu** [cannibalox/logseq-custom-files#12]
I know you haven't touched this in a while, but I really like what you did here. Any chance you can fix the sidebar script for it to work in the new version? it looks like this to me:
![image](https://github.com/cannibalox/logseq-custom-files/assets/20868562/750a87df-d2a8-4cec-8bc6-27dfab7af012)
Thanks in advance, and I understand if you have moved on to other things. I'll be using the tools without the sidebar until then.

**Comment by cannibalox** [comment]
hey @Cacuu  sorry for the lack of updates (I'm still using ls 0.9.x for work and was reluctant to upgrade).

I've pushed some changes to the css, hopefully it should now work again in logseq 0.10.x -- the new csss will not work with older logseq versions. 
closing this issue for now, but please let me know if you encounter any issues. thank you !
