### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by dominiwe** [cannibalox/logseq-custom-files#3]
I took some of your code here (mainly the part which makes namespaces more pleasant) and changed it a little for a theme I am working on.

I would like to put my theme on GitHub but unfortunately this repository does not contain a license. Because there is no license, your code is not open source nor free. So I cannot use, redistribute or modify it.

I would recommend that you add an [open source license](https://choosealicense.com/), which would allow me to reuse some of your code while you still retain the copyright. Thank you :)

**Comment by cannibalox** [comment]
done, sorry for the long wait...
