### ISSUE TITLE
How to use the new features?

### ISSUE THREAD

**Issue by bendzg** [cannibalox/logseq-custom-files#5]
I was wondering how to add the new features like the background image and properties for references.

**Comment by cannibalox** [comment]
these were just experiments to add a relevant `data-refs-self` attribute to properties :
the logseq DOM is like this:
![ss_20230125_NUC8_ugzRHjhaHd](https://user-images.githubusercontent.com/4605693/215280140-8a70bac2-7e16-4665-9782-235145364ae7.png)
the custom.js adds attributes with the name of the property key
![ss_20230125_NUC8_3b4woAfCE3](https://user-images.githubusercontent.com/4605693/215280161-dcd8a55a-9f8b-4c2b-85b2-a6a8d289c52b.png)

then it's easier to manipulate or style the page based on properties. 
For instance, the property `bg-pic:: ![](link_to_image)` lets you embed an image that will be displayed ad the page background :
usage: add `bg-pic:: ![](https://images.unsplash.com/photo-1521106581851-da5b6457f674?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwyNDYwNDl8MHwxfHNlYXJjaHwyfHxjYXZlfGVufDB8fHx8MTY3NDYwMjc2MA&ixlib=rb-4.0.3&q=80&w=1920)` and it will show up as
![ss_Logseq_Indiana_Jones_and_the_Raiders_of_the_Lost_Ark_ 19_20230125_isdqZo6IVN](https://user-images.githubusercontent.com/4605693/215280008-03d7ce9f-49c8-416c-a177-5b5914c044f7.jpg)
it works well with the unsplash plugin, just make sure to edit the end of the url where it says 'w=400`, adjust it to the width of the page 

 that being said, I believe some plugins like awesome UI/styler also let you add banners and background images with a proper ui.
